version: "3"

set: [pipefail]

tasks:
  default:
    cmds:
      - yarn start --host 0.0.0.0
  # Ensure people new to go-task and used to 'make help' have an easier time
  help:
    desc: Show how to list available tasks
    cmds:
      - |
        echo "Use 'go-task -l/--list' to list available tasks."

  deploy:
    desc: Trigger a GH Pages deployment by pushing a new tag for the lastest commit in master. Don't repeatedly tag the same commit with this task, start the deploy Action if needed.
    preconditions:
      - sh: git switch master
      - sh: git pull origin master
    vars:
      NEW_VERSION_NUMBER:
        sh: git describe --abbrev=0  | cut --delimiter "v" --fields 2- | xargs -n 1 expr 1 + # get the latest tag | trim off "v" | increment the result by 1
    cmds:
      - git tag -a v{{.NEW_VERSION_NUMBER}} -m ""
      - git push --tags



  # Tidy up the allowed-words list
  tidy-words:
    desc: Tidy and sort the allowed-words list
    env:
      TARGET: .cspell-allowed-words.txt
    cmds:
      - awk -i inplace '{print tolower($0)}' $TARGET
      - sort -o $TARGET $TARGET
      - awk -i inplace '!seen[$0]++' $TARGET

  # Run cspell on all .md/mdx docs in the project. Should use project configuration with allow-word list
  spellcheck:
    desc: Run cspell on all .md* files
    shopt: [globstar]
    cmds:
      - cmd: yarn cspell lint **/*.md*
        ignore_error: true

    # Run prettier on all md/mdx files, note prettier behaviour is set in .prettier* files
  lint:
    desc: Run prettier on all .md* files
    cmds:
      - cmd: yarn prettier
